POST https://api.umbraco.io/forms/e644a504-a515-4974-ac9a-b8a9be734edc/entries HTTP/1.1
content-type: application/json
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}

{
  "reportTitle": "Edna Test",
  "reportOptions": "Andet",
  "reportMessage": "test100",
}
###
GET https://api.umbraco.io/forms HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}

###
PUT https://api.umbraco.io/member/Emma HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}
content-type: application/json

{
    "comments": "Student",
    "email": "emma@gmail.com",
    "isApproved": true,
    "isLockedOut": false,
    "memberTypeAlias": "Member",
    "username": "Emma",
    "name": "Emma Nørregaard",
    "memberEducationInstitution": "SDU"

}

###
GET https://api.umbraco.io/member/test HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}


###
POST https://api.umbraco.io/member/test/password HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}
content-type: application/json

{
    "currentPassword": "12345670",
    "newPassword": "zaq12wsx123456"
}

###
DELETE https://api.umbraco.io/member/Emma HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}

###
POST https://ba-project-wu-memomd.netlify.app/api/auth/callback/credentials HTTP/1.1
content-type: application/x-www-form-urlencoded

csrfToken=e8aac9cf8dd000fe6452ee95a206c30993e200efa282463e12084e6e5585b212&username=Emma&password=1234567890