POST https://api.umbraco.io/forms/e644a504-a515-4974-ac9a-b8a9be734edc/entries HTTP/1.1
content-type: application/json
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}

{
  "reportTitle": "Edna Test",
  "reportOptions": "Andet",
  "reportMessage": "test100",
}
###
GET https://api.umbraco.io/forms HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}

###
PUT https://api.umbraco.io/member/Emma HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}
content-type: application/json

{
    "comments": "Student",
    "email": "emma@gmail.com",
    "isApproved": true,
    "isLockedOut": false,
    "memberTypeAlias": "Member",
    "username": "Emma",
    "name": "Emma Nørregaard",
    "memberEducationInstitution": "SDU"

}

###
GET https://api.umbraco.io/member/test HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
Authorization: Bearer CfDJ8Jvylx4k3kBAuxuSjBt4vFip681CBsNJ9DCxVE2m7yWZuAM59uo-0A53pdpmp7kTftko_sXIB5XTv8TlFELK-yFwxwX0dtqMPmwnmemiQJhZ0T4nbWo7xA3IWAfEM7FNNzXmvGMuHUjhuGUi4ynPl7KupYhaibqJ2uZOpInShvbrggJzgyqCwduBXXocj3T-ciQ8sx5dPsuAJ-F9jrq8RPjkx--y-bTC43dOJAlNiKEHzrInYbXArmOHLUgS7MmaTXKlfxVhTd002FybRWjAnacO_4hcsueJB6XQJQmO45yX1SkQC1SMLqd4xlFdPPCZfeWjl6dvHUxlHjTVQrokjz5okEIgd5PjFGlnmgfdVeFh9glt2AB4kL8ElPeK3hKH3jnj4PvRsQXL5LGMf8l1KH4avDAqpUUjHxFHRPBjpOn7


###
POST https://api.umbraco.io/member/test/password HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}
content-type: application/json

{
    "currentPassword": "12345670",
    "newPassword": "zaq12wsx123456"
}

###
DELETE https://api.umbraco.io/member/Emma HTTP/1.1
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}

###
GET http://172.24.144.1:3000/api/auth/csrf

###
POST http://172.24.144.1:3000/api/auth/callback/credentials HTTP/1.1
content-type: application/x-www-form-urlencoded

csrfToken=d4c06744844d145de010721c32a55b6d1c7f84e8de253687e85deebdde2a06a8&username=Emma&password=1234567890

###
GET https://ba-project-wu-memomd.netlify.app/api/auth/csrf

###
POST https://ba-project-wu-memomd.netlify.app/api/auth/callback/credentials HTTP/1.1
content-type: application/x-www-form-urlencoded

csrfToken=5f4fb53843ec71736c4d9923eabafae5e52fbd21a2ab48acb63afeec54acd7e3&username=Emma&password=1234567890

###
POST https://cdn.umbraco.io/member/oauth/token  HTTP/1.1
umb-project-alias: nicole-ba-test
content-type: application/x-www-form-urlencoded

grant_type=password&username=edna&password=1q2w3e4r5t6y

###
GET https://cdn.umbraco.io/media/12b813af-0670-45d0-ad4a-02e1eb24294e
umb-project-alias: nicole-ba-test
Authorization: Bearer CfDJ8Jvylx4k3kBAuxuSjBt4vFip681CBsNJ9DCxVE2m7yWZuAM59uo-0A53pdpmp7kTftko_sXIB5XTv8TlFELK-yFwxwX0dtqMPmwnmemiQJhZ0T4nbWo7xA3IWAfEM7FNNzXmvGMuHUjhuGUi4ynPl7KupYhaibqJ2uZOpInShvbrggJzgyqCwduBXXocj3T-ciQ8sx5dPsuAJ-F9jrq8RPjkx--y-bTC43dOJAlNiKEHzrInYbXArmOHLUgS7MmaTXKlfxVhTd002FybRWjAnacO_4hcsueJB6XQJQmO45yX1SkQC1SMLqd4xlFdPPCZfeWjl6dvHUxlHjTVQrokjz5okEIgd5PjFGlnmgfdVeFh9glt2AB4kL8ElPeK3hKH3jnj4PvRsQXL5LGMf8l1KH4avDAqpUUjHxFHRPBjpOn7

###
GET https://cdn.umbraco.io/content/a157b211-b293-4192-b36b-2655e3b8d7d1/children
umb-project-alias: {{$dotenv UMBRACO__PROJECTALIAS}} 
api-key:  {{$dotenv UMBRACO__APIKEY }}
accept-language: da-DK,da;q=0.9,en-DK;q=0.8,en;q=0.7,en-US;q=0.6

